api:
    image: tomcat
    ports:
        - "8000:8080"
    volumes:
        - ./build/libs/features-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/task.war
    links:
        - "db:database"
   
db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: "task"
        MYSQL_USER: "task"
        MYSQL_PASSWORD: "task"
        MYSQL_ROOT_PASSWORD: "root"
    volumes:
        - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql